development:
  adapter: postgresql
  database: test_db
  pool: 5
  timeout: 5000
  username: 'postgres'
  password: 'nadine'
# test:
#   adapter: postgresql
#   database: my_database_test
#   pool: 5
#   timeout: 5000

# production:
#   adapter: postgresql
#   database: my_database_production
#   pool: 5
#   timeout: 5000