# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd7c4bcb636ab2d37a8d3e487a01b4842a6890a10ffe3cc578bbe7171d24f61f8b0a8f8e0a0eddc7d5a89184c8a7af3b59877b260be388feeda094688ec8eeda

test:
  secret_key_base: 6f0d9164b888147e1b343db7297333ff02d12558b8ac52a79b07ede7827dfc913affff2089a8c29fa6037e79673b5fd365e4f0efc7e98ce95f8f446ad8f6f2ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
